
export const translations = {
  en: {
    welcome: "Welcome back, Trader",
    subtitle: "Here's your trading performance for this week.",
    dashboard: "Dashboard",
    analyzer: "AI Analyzer",
    journal: "Journal",
    calendar: "Economic Cal",
    settings: "Settings",
    terminal: "Terminal",
    liveCharts: "Live Charts",
    hits: "Hits (Wins)",
    misses: "Misses (Losses)",
    totalTrades: "Total Trades",
    winRate: "Win Rate",
    totalPL: "Total P&L",
    recentAnalysis: "Recent Analysis",
    generatePlan: "Generate Trade Plan",
    uploadChart: "Drop your chart here",
    technicalReasoning: "Technical Reasoning",
    saveToJournal: "Save to Journal",
    upgrade: "Upgrade Now",
    premiumPlan: "Premium Plan",
    economicPlan: "Economic Plan",
    proStatus: "Pro Status",
    login: "Login",
    email: "Email Address",
    password: "Password",
    adminPass: "Admin Password: 101010",
    enter: "Enter",
    realTimeChart: "Real-time Reference & Tools",
    pricingTitle: "Subscription Plans",
    premiumPrice: "R$90/month",
    economicPrice: "R$35/month",
    pair: "Pair",
    bias: "Bias",
    entry: "Entry",
    stopLoss: "Stop Loss",
    takeProfit: "Take Profit",
    pixPayment: "Payment via Pix",
    pixKey: "Pix Key (Phone):",
    copyPix: "Copy Key",
    billingInfo: "Billing Information",
    activeAssets: "Active Assets: BTCUSD, XAUUSD, GBPUSD, EURUSD, USDJPY",
    detailedAnalysis: "Long Analysis & Strategy",
    mtfGuideTitle: "How MTF Analysis Works",
    mtfGuideH1: "H1: Market Structure & Trend Anchor",
    mtfGuideM15: "M15: Precise Entry & Refined Trigger",
    mtfGuideConfluence: "AI calculates the convergence between both timeframes for high-probability setups.",
    riskManagement: "Capital Shield & Management",
    accountBalance: "Account Balance ($)",
    riskPercentage: "Risk Per Trade (%)",
    positionSize: "Calculated Lot Size",
    confidence: "Confidence Score",
    checklistTitle: "Pre-Trade Safety Checklist",
    checkNews: "No High-Impact News in 60m",
    checkEmotion: "I am emotionally neutral",
    checkPlan: "Followed my strategy rules",
    newsGuard: "AI News Guard",
    highImpactAlert: "HIGH IMPACT NEWS DETECTED",
    safeToTrade: "Market Environment: Safe",
    unsafeToTrade: "Market Environment: Volatile",
    newsImpactMatrix: "News Impact Matrix",
    marketSentiment: "Market Sentiment",
    volatilityWarning: "Volatility may override technicals",
  },
  pt: {
    welcome: "Bem-vindo de volta, Trader",
    subtitle: "Aqui está seu desempenho comercial esta semana.",
    dashboard: "Painel",
    analyzer: "Analisador IA",
    journal: "Diário",
    calendar: "Cal. Econômico",
    settings: "Configurações",
    terminal: "Terminal",
    liveCharts: "Gráficos Ao Vivo",
    hits: "Acertos (Ganhos)",
    misses: "Erros (Perdas)",
    totalTrades: "Total de Trades",
    winRate: "Taxa de Acerto",
    totalPL: "P&L Total",
    recentAnalysis: "Análises Recentes",
    generatePlan: "Gerar Plano de Trade",
    uploadChart: "Solte seu gráfico aqui",
    technicalReasoning: "Raciocínio Técnico",
    saveToJournal: "Salvar no Diário",
    upgrade: "Atualizar Agora",
    premiumPlan: "Plano Premium",
    economicPlan: "Plano Econômico",
    proStatus: "Status Pro",
    login: "Entrar",
    email: "Endereço de E-mail",
    password: "Senha",
    adminPass: "Senha Admin: 101010",
    enter: "Entrar",
    realTimeChart: "Gráfico em Tempo Real e Ferramentas",
    pricingTitle: "Planos de Assinatura",
    premiumPrice: "R$90/mês",
    economicPrice: "R$35/mês",
    pair: "Par",
    bias: "Viés",
    entry: "Entrada",
    stopLoss: "Stop Loss",
    takeProfit: "Take Profit",
    pixPayment: "Pagamento via Pix",
    pixKey: "Chave Pix (Celular):",
    copyPix: "Copiar Chave",
    billingInfo: "Informações de Faturamento",
    activeAssets: "Ativos Principais: BTCUSD, XAUUSD, GBPUSD, EURUSD, USDJPY",
    detailedAnalysis: "Análise Longa e Estratégia",
    mtfGuideTitle: "Como funciona a análise MTF",
    mtfGuideH1: "H1: Estrutura de Mercado e Âncora de Tendência",
    mtfGuideM15: "M15: Entrada Precisa e Gatilho Refinado",
    mtfGuideConfluence: "A IA calcula a convergência entre os tempos para setups de alta probabilidade.",
    riskManagement: "Escudo de Capital e Gestão",
    accountBalance: "Saldo da Conta ($)",
    riskPercentage: "Risco por Trade (%)",
    positionSize: "Tamanho do Lote Sugerido",
    confidence: "Score de Confiança",
    checklistTitle: "Checklist de Segurança",
    checkNews: "Sem notícias de alto impacto em 60m",
    checkEmotion: "Estou emocionalmente neutro",
    checkPlan: "Seguindo as regras da estratégia",
    newsGuard: "Escudo de Notícias IA",
    highImpactAlert: "NOTÍCIA DE ALTO IMPACTO DETECTADA",
    safeToTrade: "Ambiente de Mercado: Seguro",
    unsafeToTrade: "Ambiente de Mercado: Volátil",
    newsImpactMatrix: "Matriz de Impacto de Notícias",
    marketSentiment: "Sentimento de Mercado",
    volatilityWarning: "Volatilidade pode anular o técnico",
  }
};
